import React,{useState,useMemo,useEffect} from 'react';
import {PIPELINE_DEFAULTS,PIPELINE_PRODUCTS,PIPELINE_STATUSES,pipelineScenario,pipelineGroupKey} from '../analytics/pipelines.mjs';
import '../styles/pipelines.css';
const labels={oil:'Нефть',gas:'Газ',condensate:'Конденсат',products:'Нефтепродукты',other:'Прочее',operating:'Действует',construction:'Строится',proposed:'Проект',idle:'Простой',retired:'Закрыт',unknown:'Неизвестно',design:'Проектная',available:'Доступная',technical:'Техническая',forecast:'Прогноз',actual:'Факт',estimated:'Оценка'};
const fmt=v=>v===null||v===undefined?'Нет данных':typeof v==='number'?v.toLocaleString('ru-RU',{maximumFractionDigits:2}):String(v);
const measurement=(p,prefix)=>p[`${prefix}_value`]===null?'Нет данных':`${fmt(p[`${prefix}_value`])} ${p[`${prefix}_unit`]||'единица неизвестна'} · ${p[`${prefix}_period`]||'период неизвестен'} · ${labels[p[`${prefix}_kind`]]||'тип не указан'}`;
function Bars({entries,onSelect}){const max=Math.max(1,...entries.map(x=>x.value));return <div className="pipeline-bars">{entries.map(x=><button key={x.label} type="button" onClick={()=>onSelect?.(x)} disabled={!onSelect}><span>{x.label}</span><i style={{width:`${x.value/max*100}%`}}/><strong>{fmt(x.value)}</strong></button>)}</div>;}
export function PipelineCard({p}){
 const [percent,setPercent]=useState(70),[scenario,setScenario]=useState(false);const result=pipelineScenario(p,percent);
 return <section className="pipeline-card" data-pipeline-id={p.id}><h3>{p.name}</h3>
  <dl>{[['Продукт',labels[p.product]],['Статус',labels[p.status]],['Оператор',p.operator],['Владельцы',p.owners?.join('; ')],['Страны',p.countries.join('; ')],['Длина по источнику, км',p.length_km],['Оценка по геометрии, км',p.geometry_length_estimate_km],['Мощность',measurement(p,'capacity')],['Фактический/исходный поток',measurement(p,'throughput')],['Загрузка, %',p.utilization_pct],['Свободная мощность',p.spare_capacity===null?null:`${fmt(p.spare_capacity)} ${p.capacity_normalized_unit}`],['Год ввода',p.commissioning_year],['Источник',p.source],['Версия набора',p.source_release],['Дата записи',p.source_date],['Точность по источнику',p.geometry_accuracy],['Источник мощности',p.capacity_source],['Источник потока',p.throughput_source],['Условия газа: мощность / поток',[p.capacity_standard_conditions,p.throughput_standard_conditions].filter(Boolean).join(' / ')],['Плотность, кг/м³',p.density_kg_m3],['Источник плотности',p.density_source]].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{fmt(value||value===0?value:null)}</dd></div>)}</dl>
  {p.utilization_pct===null&&<p className="pipeline-note">Нет данных о загрузке: требуются сопоставимая мощность и фактический поток одного периода.</p>}
  {!!p.data_quality.anomalies.length&&<p role="status" className="pipeline-warning">Аномалия: поток превышает мощность. Значение не ограничено 100%.</p>}
  {!!p.attribute_conflicts.length&&<p className="pipeline-warning">Противоречивые сегменты: {p.attribute_conflicts.join(', ')}</p>}
  <p className="pipeline-note">Маршрут может быть приблизительным. Длина по геометрии — оценка, а не паспортная длина; точные координаты не публикуются в карточке.</p>
  {p.source_url&&<a href={p.source_url} target="_blank" rel="noopener noreferrer">Открыть источник ↗</a>}
  <details><summary>Исходные свойства ({p.original_properties.length})</summary><pre>{JSON.stringify(p.original_properties,null,2)}</pre></details>
  <details onToggle={e=>setScenario(e.currentTarget.open)}><summary>Сценарный анализ — не факт</summary>{scenario&&<div className="pipeline-scenario"><strong>Сценарий, не фактические данные</strong><label>Гипотетическая загрузка, %<input type="number" min="0" max="100" value={percent} onChange={e=>setPercent(e.target.value)}/></label>{result?<p>Расчётный поток: {fmt(result.flow)} {result.unit}. Основа: {measurement(p,'capacity')}. Не включён в статистику.</p>:<p>Сценарий недоступен: нужна известная мощность и загрузка от 0 до 100%.</p>}</div>}</details>
 </section>;
}
export default function PipelineAnalytics({model:m,onClose}){
 const [sort,setSort]=useState('name'),[descending,setDescending]=useState(false),[page,setPage]=useState(0);
 const f=m.filters,s=m.summary,selected=m.records.find(p=>p.id===m.selected),comparison=m.records.filter(p=>m.compare.includes(p.id));
 const update=(key,value)=>m.setFilters(prev=>({...prev,[key]:value}));
 useEffect(()=>setPage(0),[m.filters,sort,descending]);
 const sorted=useMemo(()=>[...m.filtered].sort((a,b)=>{const x=a[sort],y=b[sort];if(x===null)return y===null?0:1;if(y===null)return -1;return (typeof x==='number'?x-y:String(x).localeCompare(String(y),'ru'))*(descending?-1:1);}),[m.filtered,sort,descending]);
 useEffect(()=>{const index=sorted.findIndex(p=>p.id===m.selected);if(index>=0)setPage(Math.floor(index/25));},[m.selected,sorted]);
 const dropdown=(key,label,values)=><label>{label}<select value={f[key]} onChange={e=>update(key,e.target.value)}><option value="">Все</option>{values.map(v=><option key={v} value={v}>{labels[v]||v}</option>)}</select></label>;
 const range=(a,b,label,disabled=false)=><fieldset disabled={disabled}><legend>{label}</legend><input aria-label={`${label}: от`} type="number" min="0" placeholder="От" value={f[a]} onChange={e=>update(a,e.target.value)}/><input aria-label={`${label}: до`} type="number" min="0" placeholder="До" value={f[b]} onChange={e=>update(b,e.target.value)}/></fieldset>;
 return <aside className="panel pipeline-panel" aria-label="Аналитика трубопроводов"><header><h2>Аналитика трубопроводов</h2><button aria-label="Закрыть аналитику трубопроводов" onClick={onClose}>×</button></header>
  <details><summary>Данные и локальное открытие</summary><p>Публичные слои требуют подтверждённых прав и версии источника. Локальные GeoJSON остаются в этом браузере: не загружаются на сервер и не включаются в публикацию.</p>{['oil','gas'].map(type=><label key={type}>{labels[type]}: открыть GeoJSON<input aria-label={`Локальный GeoJSON: ${labels[type]}`} type="file" accept=".geojson,.json" onChange={e=>m.importFile(e.target.files[0],type)}/></label>)}</details>
  {m.local&&<p className="pipeline-note">Локальный просмотр · данные не опубликованы</p>}
  {m.loading&&<p role="status">Загрузка и проверка данных…</p>}{m.error&&<p role="alert">{m.error} <button onClick={m.retry}>Повторить</button></p>}
  {!m.loading&&!m.records.length&&<p>Нет разрешённых опубликованных маршрутов. Откройте локальные файлы для анализа.</p>}
  <div className="pipeline-filters"><label>Поиск<input aria-label="Поиск трубопроводов" placeholder="Название, оператор, страна" value={f.query} onChange={e=>update('query',e.target.value)}/></label>
   {dropdown('product','Продукт',PIPELINE_PRODUCTS)}{dropdown('status','Статус',PIPELINE_STATUSES)}{dropdown('country','Страна',[...new Set(m.records.flatMap(p=>p.countries))].sort())}
   {dropdown('unit','Единицы мощности',[...new Set(m.records.map(p=>p.capacity_normalized_unit).filter(Boolean))])}
   {range('capacityMin','capacityMax','Мощность',!f.unit)}{range('utilizationMin','utilizationMax','Загрузка, %')}{range('yearMin','yearMax','Год ввода')}
   <button onClick={()=>m.setFilters({...PIPELINE_DEFAULTS})}>Сбросить фильтры</button>
   <label>Цвет маршрутов<select value={m.color} onChange={e=>m.setColor(e.target.value)}>{[['product','Продукт'],['status','Статус'],['capacity','Мощность'],['utilization','Загрузка']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
  </div>
  <div className="pipeline-legend">{m.color==='product'?'Нефть — оранжевый; газ — синий; конденсат — фиолетовый; продукты — зелёный.':m.color==='status'?'Действует — зелёный; строится — оранжевый; проект — синий; простой — фиолетовый; закрыт — тёмный.':m.color==='utilization'?'Загрузка: ≤25% синий, ≤50% бирюзовый, ≤75% зелёный, ≤100% оранжевый, >100% красный.':`Мощность: светлый → тёмный, единицы: ${f.unit||'выберите единицы для окраски'}.`} Серый пунктир — нет сопоставимых данных. Толщина по мощности только в выбранных единицах.</div>
  <section><h3>Сводка отфильтрованных маршрутов</h3><div className="pipeline-kpis">{[['Объекты',s.total],['Действуют',s.operating],['Строятся',s.construction],['С мощностью',s.knownCapacity],['С фактическим потоком',s.knownFlow],['С загрузкой',s.knownUtilization]].map(([k,v])=><div key={k}><strong>{v}</strong>{k}</div>)}</div><p>Общая оценка длины уникальных геометрических отрезков: {fmt(s.lengthEstimate)} км. Совпадающие отрезки исключены; различная детализация геометрии может сохранять пересечения.</p></section>
  {selected&&<><button onClick={()=>m.select(null)}>Закрыть карточку</button><PipelineCard key={selected.id} p={selected}/></>}
  <details open><summary>Таблица маршрутов ({m.filtered.length})</summary><label>Сортировать<select value={sort} onChange={e=>setSort(e.target.value)}>{[['name','Название'],['product','Продукт'],['status','Статус'],['length_km','Длина'],['capacity_normalized','Мощность'],['utilization_pct','Загрузка']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><input type="checkbox" checked={descending} onChange={e=>setDescending(e.target.checked)}/>По убыванию</label><p>Мощности сортируются корректно внутри выбранных единиц. Сравнение — до 4 объектов.</p>
   <div className="pipeline-table"><table><thead><tr>{['Сравнить','Название','Продукт','Страна','Оператор','Статус','Длина, км','Мощность','Поток','Загрузка, %','Период','Источник'].map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{sorted.slice(page*25,page*25+25).map(p=><tr key={p.id} aria-selected={p.id===m.selected}><td><input aria-label={`Сравнить ${p.name}`} type="checkbox" checked={m.compare.includes(p.id)} disabled={!m.compare.includes(p.id)&&m.compare.length>=4} onChange={()=>m.setCompare(ids=>ids.includes(p.id)?ids.filter(x=>x!==p.id):[...ids,p.id])}/></td><td><button onClick={()=>m.select(p.id)}>{p.name}</button></td><td>{labels[p.product]}</td><td>{p.countries.join('; ')}</td><td>{fmt(p.operator)}</td><td>{labels[p.status]}</td><td>{fmt(p.length_km)}</td><td>{measurement(p,'capacity')}</td><td>{measurement(p,'throughput')}</td><td>{fmt(p.utilization_pct)}</td><td>{p.throughput_period||p.capacity_period||'Нет данных'}</td><td>{p.source_url?<a href={p.source_url} target="_blank" rel="noopener noreferrer">Источник ↗</a>:fmt(p.source)}</td></tr>)}</tbody></table></div>
   <div><button disabled={!page} onClick={()=>setPage(x=>x-1)}>Назад</button> {page+1} / {Math.max(1,Math.ceil(sorted.length/25))} <button disabled={(page+1)*25>=sorted.length} onClick={()=>setPage(x=>x+1)}>Далее</button></div></details>
  <details><summary>Сравнение объектов: мощность, поток и резерв</summary>{!comparison.length&&<p>Отметьте объекты в таблице.</p>}{comparison.map(p=><section key={p.id}><h4>{p.name}</h4><p>{pipelineGroupKey(p)}</p>{p.capacity_normalized===null?<p>Нет данных о мощности</p>:<Bars entries={[{label:'Мощность',value:p.capacity_normalized},...(p.utilization_pct!==null?[{label:'Фактический поток',value:p.throughput_normalized}]:[])]}/>}<p>Резерв: {fmt(p.spare_capacity)} {p.spare_capacity!==null?p.capacity_normalized_unit:''}. {p.utilization_pct===null?'Нет сопоставимого фактического потока.':''}</p></section>)}<p>Сопоставляйте только одинаковые продукты, периоды, типы мощности и стандартные условия. Шкала каждого объекта независима.</p></details>
  <details><summary>Распределение по мощности</summary>{!s.capacityGroups.length&&<p>Нет данных о мощности</p>}{s.capacityGroups.map(g=><section key={g.key}><h4>{g.key}</h4><Bars entries={g.bins.map((value,i)=>({label:`${fmt(g.max*i/4)}–${fmt(g.max*(i+1)/4)}`,value,index:i}))} onSelect={x=>{const p=m.filtered.find(p=>pipelineGroupKey(p)===g.key);m.setFilters({...PIPELINE_DEFAULTS,product:p.product,unit:p.capacity_normalized_unit,capacityMin:String(g.max*x.index/4),capacityMax:String(g.max*(x.index+1)/4)});}}/></section>)}</details>
  <details><summary>Распределение загрузки</summary><p>Средняя по сопоставимой выборке: {fmt(s.meanUtilization)}%. Покрытие: {s.knownUtilization} / {s.total}; без данных: {s.missingUtilization}.</p><Bars entries={s.utilizationBins.map((value,i)=>({label:['0–25%','>25–50%','>50–75%','>75–100%','>100%'][i],value,index:i}))} onSelect={x=>m.setFilters({...f,utilizationMin:String(x.index*25+(x.index?0.000001:0)),utilizationMax:x.index===4?'':String((x.index+1)*25)})}/></details>
  <details><summary>Количество по статусам</summary><Bars entries={Object.entries(s.statuses).map(([key,value])=>({key,label:labels[key],value}))} onSelect={x=>update('status',x.key)}/></details>
  <details><summary>География и покрытие данных</summary><p>Учитываются полные связанные маршруты, а не длина внутри границ. Трансграничные объекты входят в несколько стран. Это не суммарная национальная пропускная способность.</p><Bars entries={s.countries.map(c=>({label:c.country,value:c.count}))} onSelect={x=>update('country',x.label)}/><div className="pipeline-table"><table><thead><tr><th>Страна</th><th>Объекты</th><th>Оценка км</th><th>Мощность</th><th>Факт. поток</th></tr></thead><tbody>{s.countries.map(c=><tr key={c.country}><td>{c.country}</td><td>{c.count}</td><td>{fmt(c.lengthEstimate)}</td><td>{c.capacity}/{c.count}</td><td>{c.flow}/{c.count}</td></tr>)}</tbody></table></div></details>
  <details><summary>Качество данных</summary><p>Мощность: {s.knownCapacity}/{s.total}; фактический поток: {s.knownFlow}/{s.total}; сопоставимая загрузка: {s.knownUtilization}/{s.total}.</p><Bars entries={Object.entries(s.products).map(([key,value])=>({label:labels[key]||key,value,key}))} onSelect={x=>update('product',x.key)}/>{Object.keys(s.products).map(product=>{const rows=m.filtered.filter(p=>p.product===product);return <p key={product}>{labels[product]}: мощность {rows.filter(p=>p.capacity_normalized!==null).length}/{rows.length}, фактический поток {rows.filter(p=>p.throughput_kind==='actual'&&p.throughput_value!==null).length}/{rows.length}</p>;})}<p>Пропуски: {Object.entries(s.missing).map(([k,n])=>`${k}: ${n}`).join('; ')}</p><details><summary>Даты источников</summary>{Object.entries(s.dates).sort().map(([date,count])=><p key={date}>{date}: {count}</p>)}</details></details>
 </aside>;
}
