import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const directory = 'artifacts/oilfields';
fs.mkdirSync(directory,{recursive:true});
const browser = await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
page.setDefaultTimeout(15000);
page.setDefaultNavigationTimeout(45000);
const errors=[],checks=[];
const record = checks.push.bind(checks);
checks.push = (...items) => { console.log(...items); return record(...items); };
page.on('pageerror',error => errors.push(error.message));
page.on('console',message => { if(message.type()==='error') errors.push(message.text()); });
await page.addInitScript(() => localStorage.setItem('oil-atlas-language','en'));
await page.route('**/api/tankers',route => route.fulfill({contentType:'application/json',body:JSON.stringify({vessels:[{mmsi:'273129320',name:'GELIOTROP',imo:'9323986',flag:'Russia',vesselTypeName:'Crude Oil Tanker',lat:10,lon:10,speed:11.8,course:324,deadweight:105547,draught:8.2,destination:'KALININGRAD',cargoState:'ballast',timestamp:new Date().toISOString(),sourceAttributes:{name:'GELIOTROP',flag:'Russia',extra:'retained'}}]})}));
const mapReady = () => page.waitForFunction(() => window.__oilAtlasMap?.getLayer('oilfield-points') && window.__oilAtlasMap.isSourceLoaded('oilfields'),null,{timeout:30000});
const mapMove = async (center,zoom) => { await page.evaluate(({center,zoom}) => window.__oilAtlasMap.jumpTo({center,zoom}),{center,zoom}); await page.waitForTimeout(450); await mapReady(); };
const clickFeature = async layers => {
  const point = await page.evaluate(layers => {
    const map=window.__oilAtlasMap;
    const candidates=map.queryRenderedFeatures({layers});
    for(const feature of candidates) {
      const p=map.project(feature.geometry.coordinates);
      const element=document.elementFromPoint(p.x,p.y);
      if(element?.classList.contains('maplibregl-canvas')) return {x:p.x,y:p.y};
    }
    return null;
  },layers);
  assert.ok(point,`Clickable feature in ${layers}`);
  await page.mouse.click(point.x,point.y);
};
const fold = (className) => page.locator(`.${className} > .field-fold-toggle`);
try {
  await page.goto(process.env.OIL_ATLAS_TEST_URL || 'http://127.0.0.1:5182/',{waitUntil:'networkidle'});
  await mapReady();
  if (!process.argv.includes('--mobile')) {
  assert.equal(await page.evaluate(async()=> (await window.__oilAtlasMap.getSource('oilfields').getData()).features.length),6491);
  assert.ok(await page.evaluate(()=>window.__oilAtlasMap.queryRenderedFeatures({layers:['oilfield-clusters']}).length)>0);
  await page.screenshot({path:`${directory}/desktop.png`});
  checks.push('Full registry loads: 6,491 valid points, clusters visible, no per-object DOM markers');
  const zoomBefore=await page.evaluate(()=>window.__oilAtlasMap.getZoom());
  await clickFeature(['oilfield-clusters']);
  await page.waitForTimeout(650);
  assert.ok(await page.evaluate(()=>window.__oilAtlasMap.getZoom())>zoomBefore);
  checks.push('Cluster click expands the map');
  await mapMove([16.71667,48.41667],14);
  await clickFeature(['oilfield-points']);
  await page.locator('.selected-field-card').waitFor();
  assert.equal(await fold('selected-field-card').getAttribute('aria-expanded'),'true');
  checks.push('Map click selects oilfield in the right panel');
  await page.getByRole('button',{name:'Oilfield filters',exact:true}).click();
  await page.getByLabel('Find oilfield',{exact:true}).fill('Matzen');
  await page.getByRole('button',{name:'Apply',exact:true}).click();
  await page.getByRole('button',{name:'Matzen Austria',exact:true}).click();
  await page.waitForTimeout(850);
  assert.equal(await page.locator('[data-field-id]').getAttribute('data-field-id'),'OG0000001');
  assert.match(await page.locator('.field-detail').innerText(),/1[,\s\u00a0\u202f]501/);
  assert.equal(await page.locator('.field-source').getAttribute('href'),'https://www.gem.wiki/Matzen_Oil_and_Gas_Field_(Austria)');
  await page.getByRole('button',{name:'Oilfield filters',exact:true}).click();
  await page.locator('.field-detail h3').scrollIntoViewIfNeeded();
  await page.screenshot({path:`${directory}/field-selected.png`});
  checks.push('Name filtering and details preserve original reserves, units and source URL');
  await mapMove([10,10],6);
  await clickFeature(['tankers']);
  await page.locator('[data-tanker-id="273129320"]').waitFor();
  assert.ok(await page.locator('.selected-tanker-card').innerText().then(text=>text.includes('GELIOTROP')));
  await fold('selected-field-card').click();
  assert.equal(await fold('selected-field-card').getAttribute('aria-expanded'),'false');
  assert.equal(await fold('selected-tanker-card').getAttribute('aria-expanded'),'true');
  await fold('selected-tanker-card').focus();
  await page.keyboard.press('Enter');
  assert.equal(await fold('selected-tanker-card').getAttribute('aria-expanded'),'false');
  await fold('selected-field-card').click();
  assert.equal(await fold('selected-tanker-card').getAttribute('aria-expanded'),'false');
  await fold('selected-tanker-card').click();
  assert.equal(await page.locator('.tanker-attribute-group').count(),5);
  assert.ok(await page.locator('.selected-tanker-card').innerText().then(text=>text.includes('GELIOTROP')));
  await fold('selected-field-card').click();
  await page.screenshot({path:`${directory}/tanker-selected.png`});
  checks.push('Tanker selection preserves field and filter; five groups, independent collapse and keyboard toggling');
  await page.getByText('Map layers',{exact:true}).click();
  const layer=page.locator('.field-layer-controls');
  await layer.getByRole('checkbox',{name:'Oilfields',exact:true}).uncheck();
  await page.waitForFunction(()=>window.__oilAtlasMap.getLayoutProperty('oilfield-points','visibility')==='none');
  assert.equal(await page.locator('[data-testid="field-visible-count"]').innerText(),'0');
  await layer.getByRole('checkbox',{name:'Oilfields',exact:true}).check();
  await layer.getByRole('checkbox',{name:'Oilfield clusters',exact:true}).uncheck();
  await mapReady();
  assert.equal(await page.evaluate(()=>window.__oilAtlasMap.getStyle().sources.oilfields.cluster),false);
  await layer.getByRole('checkbox',{name:'Tankers',exact:true}).uncheck();
  assert.equal(await page.evaluate(()=>window.__oilAtlasMap.getLayoutProperty('tankers','visibility')),'none');
  await layer.getByRole('checkbox',{name:'Tankers',exact:true}).check();
  await layer.getByRole('checkbox',{name:'Oilfield analytics',exact:true}).uncheck();
  assert.equal(await page.locator('.field-kpis').count(),0);
  await layer.getByRole('checkbox',{name:'Oilfield analytics',exact:true}).check();
  await layer.getByRole('checkbox',{name:'Oilfield clusters',exact:true}).check();
  await page.getByText('Map layers',{exact:true}).click();
  checks.push('All four layer controls operate independently without deleting selected records');
  await page.getByRole('button',{name:'Oilfield filters',exact:true}).click();
  await page.getByRole('button',{name:'Reset filters',exact:true}).click();
  await mapReady();
  await mapMove([-100,35],3);
  const expected=await page.evaluate(async()=>{
    const map=window.__oilAtlasMap,bounds=map.getBounds();
    const data=await map.getSource('oilfields').getData();
    return data.features.filter(f=>bounds.contains(f.geometry.coordinates)).length;
  });
  const actual=Number((await page.locator('[data-testid="field-visible-count"]').innerText()).replace(/\D/g,''));
  assert.equal(actual,expected);
  await page.getByRole('button',{name:'Show only in current map area',exact:true}).click();
  await mapMove([110,-20],4);
  await page.waitForFunction(()=>document.querySelector('[data-testid="field-visible-count"]').textContent==='0');
  await page.getByRole('button',{name:'Reset filters',exact:true}).click();
  await page.getByRole('button',{name:'Oilfield filters',exact:true}).click();
  const countryBar=page.locator('.field-chart').filter({has:page.getByRole('heading',{name:'Top 5 countries',exact:true})}).locator('button').first();
  const countryName=(await countryBar.getAttribute('aria-label')).split(':')[0];
  await countryBar.click();
  await page.waitForFunction(name=>JSON.parse(localStorage.getItem('oil-atlas-fields-v1')).filters.country===name,countryName);
  checks.push('Viewport analytics reconciles with source; area restriction and chart click apply filters');
  await page.reload({waitUntil:'networkidle'});
  await mapReady();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('oil-atlas-fields-v1')).filters.country),countryName);
  checks.push('Filters and layer preferences persist after reload');
  }
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(400);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const rect=await page.locator('.oilfield-panel').boundingBox();
  assert.ok(rect.y>=390 && rect.y+rect.height<=845);
  await page.screenshot({path:`${directory}/mobile-open.png`});
  await page.locator('.oilfield-panel > .field-fold > .field-fold-toggle').click();
  await page.waitForTimeout(200);
  assert.ok((await page.locator('.oilfield-panel').boundingBox()).height<70);
  await page.screenshot({path:`${directory}/mobile-collapsed.png`});
  checks.push('Mobile bottom sheet opens/collapses without horizontal overflow');
  assert.deepEqual(errors,[]);
} finally {
  fs.writeFileSync(`${directory}/${process.argv.includes('--mobile') ? 'mobile-report' : 'report'}.json`,JSON.stringify({checks,errors},null,2));
  await browser.close();
}
console.log(checks.join('\n'));
