export const oilfieldsRu = {
  'Layer on':'Вкл.', 'Layer off':'Выкл.',
  'Onshore oilfields':'Наземные месторождения',
  'Offshore oilfields':'Морские месторождения',
  'Location type is estimated from coordinates and coastline; coastal locations may be inaccurate.':'Тип расположения определён приблизительно по координатам и береговой линии; возможны ошибки у побережья.',
  'Map layers':'Слои карты', 'Oilfields':'Нефтяные месторождения', 'Oilfield':'Нефтяное месторождение',
  'Oilfield clusters':'Кластеры месторождений', 'Oilfield analytics':'Аналитика месторождений',
  'Oilfield explorer':'Месторождения и суда', 'Oilfield filters':'Фильтры месторождений',
  'Find oilfield':'Поиск месторождения', 'Name or ID':'Название или ID', 'All':'Все',
  'Oilfield country':'Страна месторождения', 'Oilfield status':'Статус месторождения',
  'Object type':'Тип объекта', 'Fuel type':'Тип топлива', 'Operator':'Оператор',
  'Coordinate accuracy':'Точность координат', 'Reserves data':'Данные о запасах',
  'Production data':'Данные о добыче', 'Discovery year':'Год открытия',
  'Production start year':'Начало добычи', 'From':'От', 'To':'До',
  'Apply':'Применить', 'Reset filters':'Сбросить',
  'Show only in current map area':'Показать только в текущей области карты',
  'Clear area restriction':'Снять ограничение области', 'Found objects':'Найдено объектов',
  'With coordinates':'С координатами', 'No coordinates':'Нет координат',
  'Oilfield search results':'Результаты поиска месторождений', 'Previous':'Назад', 'Next':'Далее',
  'No open data':'Нет открытых данных', 'Basic information':'Основные данные',
  'Local name':'Местное название', 'Country':'Страна', 'Region':'Регион', 'Owner':'Собственник',
  'Parent company':'Материнская компания', 'Basin':'Бассейн', 'Block / licence':'Блок / лицензия',
  'Project / complex':'Проект / комплекс', 'FID year':'Год FID', 'Status source':'Источник статуса',
  'Status year':'Год статуса', 'Production':'Добыча', 'Reserves':'Запасы',
  'Oil production':'Добыча нефти', 'Gas production':'Добыча газа', 'Oil reserves':'Запасы нефти',
  'Gas reserves':'Запасы газа', 'Unit':'Единица измерения', 'Data year':'Год данных',
  'Reserve class':'Класс запасов', 'Open source':'Открыть источник',
  'Tanker data':'Данные танкера', 'Position and movement':'Положение и движение',
  'Voyage and destination':'Рейс и назначение', 'Technical characteristics':'Технические характеристики',
  'Source and update time':'Источник и время обновления', 'Status':'Статус', 'Under way':'На ходу',
  'Loading oilfield registry…':'Загрузка реестра месторождений…',
  'Oilfield registry unavailable':'Реестр месторождений недоступен',
  'Oilfield status legend':'Легенда статусов месторождений',
  'Visible map area and active filters':'Видимая область карты с учётом фильтров',
  'Oilfields in view':'Объектов на карте', 'Oilfield layer is hidden':'Слой месторождений выключен',
  'Status distribution':'По статусам', 'Top 5 countries':'Топ-5 стран', 'Top 5 operators':'Топ-5 операторов',
  'No objects in view':'В текущей области объектов нет', 'With reserves data':'С данными о запасах',
  'With production data':'С данными о добыче', 'Exact coordinates':'Точные координаты',
  'Approximate coordinates':'Приблизительные координаты', 'Unknown accuracy':'Точность не указана',
  'Reserves are not summed: classes, years and units differ; objects may overlap.':'Запасы не суммируются: различаются классы, годы и единицы; объекты могут пересекаться.',
  'Registry':'В реестре', 'Without valid coordinates':'Без валидных координат',
  'These records remain searchable but are not drawn on the map.':'Эти записи доступны в поиске, но не отображаются на карте.',
  'Operating':'В эксплуатации', 'In development':'В разработке', 'Discovered':'Открыто',
  'Shut in':'Приостановлено', 'Decommissioned':'Выведено из эксплуатации', 'Abandoned':'Ликвидировано',
  'Unknown status':'Статус неизвестен', 'exact':'Точные', 'approximate':'Приблизительные',
  'unknown':'Не указано', 'yes':'Есть данные', 'no':'Нет данных', 'oil and gas':'Нефть и газ',
  'oil':'Нефть', 'field':'Месторождение', 'asset':'Актив', 'pool':'Залежь', 'project':'Проект',
  'block':'Блок', 'complex':'Комплекс', 'concession':'Концессия', 'area':'Участок',
  'phase':'Этап', 'basin':'Бассейн', 'sub-basin':'Подбассейн', 'ugs':'Подземное хранилище газа',
  'exploration':'Разведка', 'Oilfield icons unavailable':'Не удалось загрузить значки месторождений',
};
