export const ru = {
  Source: "Источник",
  Records: "Записи",
  "Zoom in": "Приблизить",
  "Zoom out": "Отдалить",
  "Toggle attribution": "Показать авторство карты",
  "Capacity: mixed": "Мощность: разные годы",
  "mixed years": "разные годы",
  Capacity: "Мощность",
  production: "добыча",
  consumption: "потребление",
  "refinery inventory": "реестр НПЗ",
  "About analysis": "Описание анализа",
  "Map summary": "Итоги карты",
  "Top refinery owners": "Крупнейшие владельцы НПЗ",
  "No matching records": "Совпадений нет",
  "Country match": "Привязка страны",
  Coordinates: "Координаты",
  inside: "Внутри полигона",
  "coastal fallback": "Прибрежная привязка",
  "outside tolerance": "За пределами допустимого расстояния",
  "Capacity is the sum of known records, including closed facilities. Compare coverage:":
    "Мощность — сумма известных записей, включая закрытые объекты. Сравните покрытие:",
  "Capacity totals sum known records, including historical and closed refineries. Missing is never zero. A country without matched refineries is not proof of zero national capacity.":
    "Сумма мощности включает известные записи, исторические и закрытые НПЗ. Пропуск не равен нулю. Отсутствие привязанных НПЗ не доказывает нулевую мощность страны.",
  "Ratios requiring a full capacity denominator are withheld when any refinery capacity is missing or duplicate candidates remain. Production and consumption can refer to different years, shown in each tooltip and profile.":
    "Отношения с полной мощностью в знаменателе не рассчитываются при пропусках или возможных дублях. Добыча и потребление могут относиться к разным годам, указанным в подсказках и карточках.",
  "Approximate conversion: 1 tonne ≈ 7.33 barrels; annual tonnes × 7.33 / 365 = barrels/day. Crude density varies; capacity is not actual throughput.":
    "Приблизительный пересчёт: 1 тонна ≈ 7,33 барреля; т/год × 7,33 / 365 = барр./сут. Плотность нефти различается; мощность не равна фактической переработке.",
  "Country colors use quintiles, with a separate No data class. Negative and positive growth / inflation use a diverging scale.":
    "Цвета стран используют квинтили и отдельный класс «Нет данных». Для отрицательного и положительного роста / инфляции применяется расходящаяся шкала.",
  "Spatial join uses full source polygons, then nearest boundary within 5 km; a second candidate within 1 km of the best match is rejected. Country labels use NAME_EN.":
    "Пространственная привязка использует исходные полигоны, затем ближайшую границу в пределах 5 км. Если второй кандидат отличается менее чем на 1 км, привязка отклоняется. Подписи стран берутся из NAME_EN.",
  Overview: "Обзор",
  "Oil Balance": "Нефтяной баланс",
  "Refining Capacity": "Мощности НПЗ",
  Production: "Добыча",
  Consumption: "Потребление",
  "Refinery Infrastructure": "Инфраструктура НПЗ",
  "Refinery Age": "Возраст НПЗ",
  "Refinery Status": "Статус НПЗ",
  "Product Mix": "Структура продуктов",
  Economics: "Экономика",
  "Fuel Prices": "Цены топлива",
  Owners: "Владельцы",
  Anomalies: "Аномалии",
  "WORLD INDUSTRY INTELLIGENCE": "АНАЛИТИКА МИРОВОЙ НЕФТЯНОЙ ОТРАСЛИ",
  "GLOBAL EXPLORER": "МИРОВАЯ КАРТА",
  "The world’s refining landscape": "Мировая нефтепереработка",
  "source records": "исходных записей",
  "TOP REFINERY OWNERS": "КРУПНЕЙШИЕ ВЛАДЕЛЬЦЫ НПЗ",
  "Known capacity": "Известная мощность",
  "TOP 10": "ТОП-10",
  "EXPLORE THE INDUSTRY": "АНАЛИЗ ОТРАСЛИ",
  "Choose a lens. Read it on the map.":
    "Выберите анализ — результат появится на карте.",
  "Refining capacity": "Мощность НПЗ",
  "Total capacity": "Суммарная мощность",
  "Refinery count": "Количество НПЗ",
  "Average capacity": "Средняя мощность",
  "Median capacity": "Медианная мощность",
  "Largest refinery": "Крупнейший НПЗ",
  "Country typology": "Типология стран",
  "Refining / Consumption": "Переработка / Потребление",
  "Production / Consumption": "Добыча / Потребление",
  "Consumption / Refining": "Потребление / Переработка",
  "Total liquids": "Нефть и жидкие углеводороды",
  "Crude oil": "Сырая нефть",
  "Oil / products consumption": "Потребление нефти / нефтепродуктов",
  "Consumption per refinery": "Потребление на один НПЗ",
  "Largest refinery share": "Доля крупнейшего НПЗ",
  "Capacity concentration · HHI": "Концентрация мощностей · HHI",
  "Average reported operating age": "Средний известный срок работы",
  "Median reported operating age": "Медианный известный срок работы",
  "Refineries >": "НПЗ старше ",
  years: "лет",
  "Selected status count": "Количество НПЗ выбранного статуса",
  "Selected status share": "Доля выбранного статуса",
  "Selected status capacity": "Мощность выбранного статуса",
  Diesel: "Дизель",
  Gasoline: "Бензин",
  "Jet / Kerosene": "Авиатопливо / керосин",
  "Residual Fuel Oil": "Мазут",
  "Residual fuel": "Мазут",
  LPG: "СУГ",
  "GDP growth": "Рост ВВП",
  "GDP Growth": "Рост ВВП",
  GDP: "ВВП",
  "CPI inflation": "Инфляция ИПЦ",
  "Refining intensity": "Интенсивность переработки",
  "Consumption intensity": "Интенсивность потребления",
  "Production intensity": "Интенсивность добычи",
  "Owner refining footprint": "Мощности выбранного владельца",
  "Owner refinery count": "НПЗ выбранного владельца",
  "Country signals": "Аналитические признаки стран",
  "matching countries": "подходящих стран",
  "Raw Oil Exporter": "Экспортёр сырой нефти",
  "Refining Hub": "Центр переработки",
  "Large Consumer Market": "Крупный рынок потребления",
  "Balanced Market": "Сбалансированный рынок",
  "Import Dependent": "Зависимость от импорта",
  "Insufficient Data": "Недостаточно данных",
  "High Production + Low Refining": "Высокая добыча + низкая переработка",
  "High Refining + Low Domestic Consumption":
    "Высокая переработка + низкое внутреннее потребление",
  "High Consumption + Low Refining": "Высокое потребление + низкая переработка",
  "Many Small Refineries": "Много небольших НПЗ",
  "Few Very Large Refineries": "Несколько очень крупных НПЗ",
  "High Closed Capacity Share": "Высокая доля закрытых мощностей",
  "Old Active Refinery Fleet": "Старый действующий парк НПЗ",
  "Large Refining Surplus": "Большой избыток мощностей",
  "Large Refining Deficit": "Большой дефицит мощностей",
  INDICATOR: "ПОКАЗАТЕЛЬ",
  STATUS: "СТАТУС",
  SIGNAL: "ПРИЗНАК",
  "PRICE UNIT": "ЕДИНИЦА ЦЕНЫ",
  BASEMAP: "ПОДЛОЖКА",
  "All statuses": "Все статусы",
  Active: "Действующий",
  Closed: "Закрыт",
  Modernization: "Модернизация",
  Unknown: "Неизвестно",
  "Reset View": "Сбросить вид",
  "Clear owner filter": "Сбросить владельца",
  "Clear search": "Очистить поиск",
  "Owner:": "Владелец:",
  "Status:": "Статус:",
  "Country:": "Страна:",
  "No data": "Нет данных",
  "No price units in source": "В источнике нет единиц цены",
  "Choose source unit": "Выберите единицу",
  "Source years:": "Годы источников:",
  "details on hover": "подробности при наведении",
  "Source owner groups; joint ventures are not split into equity shares.":
    "Группы владельцев из источника; доли участия в СП не распределяются.",
  "Largest:": "Крупнейший:",
  "Capacity coverage:": "Покрытие мощностей:",
  "Age coverage:": "Покрытие возраста:",
  "countries with data": "стран с данными",
  "quintile classes": "классы по квинтилям",
  "negative / positive": "отрицательные / положительные",
  "Breaks:": "Границы классов:",
  "selected signal": "выбранный признак",
  "No verified fuel prices in source":
    "В источнике нет подтверждённых цен топлива",
  "Square-root symbols · historical & current capacity":
    "Размер по √мощности · исторические и текущие данные",
  "Exploratory ratios across source years, not a same-year balance.":
    "Отношения разных лет; это не баланс за один год.",
  Refineries: "НПЗ",
  refineries: "НПЗ",
  "refinery inventory; capacity years vary":
    "реестр НПЗ; годы мощности различаются",
  "Refinery inventory · status 2026; capacity years vary":
    "Реестр НПЗ · статус на 2026; годы мощности различаются",
  "Inventory status: 2026 · capacity years vary":
    "Статус на 2026 · годы мощности различаются",
  "status · 2026; capacity years vary":
    "статус на 2026; годы мощности различаются",
  "status · 2026": "статус на 2026",
  "production / consumption years": "годы добычи / потребления",
  "capacity inventory / consumption year": "реестр мощностей / год потребления",
  "consumption / capacity inventory": "потребление / реестр мощностей",
  "capacity inventory / GDP year": "реестр мощностей / год ВВП",
  "consumption / GDP years": "годы потребления / ВВП",
  "production / GDP years": "годы добычи / ВВП",
  "reported lifetime / 2026 for active plants":
    "известный срок работы / 2026 для действующих НПЗ",
  "source date": "дата источника",
  "source unit": "единица источника",
  "capacity years vary": "годы мощности различаются",
  "capacity records · includes closed / possible duplicate sites":
    "записей мощности · включая закрытые / возможные дубли",
  "Recorded Mt/year": "Учтено, млн т/год",
  Countries: "Страны",
  countries: "стран",
  "Mt/year": "млн т/год",
  "bbl/day/refinery": "барр./сут. на НПЗ",
  "bbl/day": "барр./сут.",
  "billion USD": "млрд USD",
  "t/year": "т/год",
  category: "категория",
  "Search country, refinery or owner": "Поиск страны, НПЗ или владельца",
  "Search country, refinery, owner": "Страна, НПЗ или владелец",
  "No matching results": "Совпадений нет",
  Country: "Страна",
  Refinery: "НПЗ",
  Owner: "Владелец",
  "COUNTRY PROFILE": "ПРОФИЛЬ СТРАНЫ",
  "REFINERY PROFILE": "ПРОФИЛЬ НПЗ",
  "Compare countries": "Сравнить страны",
  "COMPARE COUNTRIES": "СРАВНЕНИЕ СТРАН",
  "Compare with": "Сравнить с",
  "Choose another country": "Выберите другую страну",
  Indicator: "Показатель",
  "Number of refineries": "Количество НПЗ",
  "Active refineries": "Действующие НПЗ",
  "Average refinery size": "Средняя мощность НПЗ",
  "Oil production": "Добыча нефти",
  "Known recorded capacity": "Известная учтённая мощность",
  "Gasoline price": "Цена бензина",
  "Diesel price": "Цена дизеля",
  "Unit unavailable": "Единица не указана",
  "Date unavailable": "Дата не указана",
  "Year unavailable": "Год не указан",
  "Product consumption mix": "Структура потребления продуктов",
  "Missing shares are not imputed or rescaled to 100%.":
    "Пропущенные доли не заполняются и не приводятся к 100%.",
  "Similar countries": "Похожие страны",
  "Analytical signals": "Аналитические признаки",
  "Insufficient shared data (minimum 6 features).":
    "Недостаточно общих данных (нужно минимум 6 признаков).",
  "Standardized Euclidean distance; lower is closer. Mixed source years.":
    "Нормированное евклидово расстояние: меньше — ближе. Годы источников различаются.",
  features: "признаков",
  "All source fields & references": "Все поля и ссылки источника",
  "Source ": "Источник ",
  "Capacity coverage": "Покрытие мощностей",
  "records · includes historical / closed sites.":
    "записей · включая исторические / закрытые объекты.",
  "Complete within this inventory.": "Данные полны в пределах этого реестра.",
  "Missing capacity or duplicate candidates: dependent ratios are unavailable.":
    "Есть пропуски мощности или возможные дубли: зависимые отношения не рассчитаны.",
  "records need duplicate / shared-capacity review. Recorded sums may overcount.":
    "записей требуют проверки дублей / общей мощности. Суммы могут быть завышены.",
  "Reported / converted capacity · reference years vary":
    "Мощность из источника / пересчёта · годы различаются",
  "Reported operating age": "Известный срок эксплуатации",
  "Unmatched country": "Страна не определена",
  "Possible duplicate or shared complex capacity. This record is retained for review; its reported capacity may overlap another record.":
    "Возможный дубль или общая мощность комплекса. Запись сохранена для проверки; её мощность может совпадать с другой записью.",
  "Short and detailed source statuses conflict. Classification follows the short “Статус” field.":
    "Краткий и подробный статусы расходятся. Классификация использует краткое поле «Статус».",
  "Data quality & methodology": "Качество данных и методология",
  "Data quality": "Качество данных",
  "DATA QUALITY / METHODOLOGY": "КАЧЕСТВО ДАННЫХ / МЕТОДОЛОГИЯ",
  "Know the limits": "Ограничения данных",
  "Total refinery records": "Всего записей НПЗ",
  "Matched to countries": "Привязаны к странам",
  "Unmatched refineries": "НПЗ без привязки",
  Unmatched: "Без привязки",
  "Coastal fallback ≤5 km": "Прибрежная привязка ≤5 км",
  "Missing capacity": "Нет мощности",
  "Missing owner": "Нет владельца",
  "Unknown status": "Неизвестный статус",
  "Missing reliable age": "Нет достоверного возраста",
  "Invalid coordinates": "Некорректные координаты",
  "Duplicate candidates": "Возможные дубли",
  "Shared-capacity candidates": "Возможная общая мощность",
  "Conflicting statuses": "Конфликты статусов",
  "Fuel price records": "Записи цен топлива",
  "How to read the map": "Как читать карту",
  "Duplicate and shared-capacity review": "Проверка дублей и общей мощности",
  "Status conflicts": "Конфликты статусов",
  "Unrecognized statuses:": "Нераспознанные статусы:",
  "Download diagnostics JSON": "Скачать диагностику JSON",
  None: "Нет",
  "Records ": "Записи ",
  "Atlas · clean": "Атлас · без подложки",
  "Esri World Imagery": "Спутник Esri",
  "key required": "нужен ключ",
  "CARTO requires a provider API key. Showing the local Atlas map; configure VITE_CARTO_API_KEY.":
    "Для CARTO нужен ключ провайдера. Показана локальная карта; настройте VITE_CARTO_API_KEY.",
  "Basemap unavailable. Local countries and refineries remain available.":
    "Подложка недоступна. Локальные страны и НПЗ доступны.",
  "WebGL unavailable:": "WebGL недоступен:",
  "Open analytics menu": "Открыть меню анализа",
  "Close analytics menu": "Закрыть меню анализа",
  "Toggle owners": "Свернуть / развернуть владельцев",
  "Close details": "Закрыть карточку",
  "Close comparison": "Закрыть сравнение",
  "Close data quality": "Закрыть качество данных",
  "Open data quality": "Открыть качество данных",
  "Status filter": "Фильтр статуса",
  "Anomaly category": "Категория аномалии",
  "Price unit": "Единица цены",
  Basemap: "Подложка",
  "Map controls": "Управление картой",
  "Map legend": "Легенда карты",
  "Country details": "Карточка страны",
  "Refinery details": "Карточка НПЗ",
  "Country comparison": "Сравнение стран",
  "Analytics modes": "Режимы анализа",
  "Interactive world oil map": "Интерактивная нефтяная карта мира",
  "Dismiss map notice": "Закрыть сообщение карты",
  "Preparing the world view…": "Подготовка карты мира…",
  "Unable to open Oil Atlas": "Не удалось открыть Oil Atlas",
  Reload: "Перезагрузить",
  Retry: "Повторить",
  "Close analysis": "Закрыть анализ",
  "Reset View": "Сбросить вид",
  "Young → old refineries": "Молодые → старые НПЗ",
  "Lower → higher capacity": "Меньшая → большая мощность",
  "Satellite": "Космос",
  "Topographic": "Топо",
};
