export const tradeRu = {
  'Latest complete annual data · JODI / OPEC':'Последние полные годы · JODI / ОПЕК',
  'Export gaps use OPEC ASB 2025 (2024 data); the newer annual observation wins, with JODI preferred on equal years. OPEC may include condensate, transit and re-exports.':'Для пробелов в экспорте использован ОПЕК ASB 2025 (данные за 2024 год). Выбрано более новое годовое значение; при равном годе приоритет JODI. Данные ОПЕК могут включать конденсат, транзит и реэкспорт.',
  'Oil exports and imports':'Экспорт и импорт нефти',
  'Crude oil exports':'Экспорт сырой нефти',
  'Petroleum product exports':'Экспорт нефтепродуктов',
  'Crude oil imports':'Импорт сырой нефти',
  'Petroleum product imports':'Импорт нефтепродуктов',
  'Crude oil refinery intake':'Переработка сырой нефти на НПЗ',
  'Petroleum product demand':'Потребление нефтепродуктов — всего',
  'Gasoline demand':'Потребление бензина',
  'Diesel / gasoil demand':'Потребление дизеля / газойля',
  'LPG demand':'Потребление СУГ',
  'Jet fuel demand':'Потребление авиакеросина',
  'Fuel oil demand':'Потребление мазута',
  'Naphtha demand':'Потребление нафты',
  'Assessment codes':'Оценка качества',
  'No complete year (2021–2025)':'Нет полного года за 2021–2025',
  'Country ranking':'Рейтинг стран',
  'Countries with data':'Стран с данными',
  'Year':'Год',
  'Show all countries':'Показать все страны',
  'Show top 20':'Показать первые 20',
  'Latest complete years; country years may differ. This is not a same-year global ranking.':'Последние полные годы могут различаться по странам. Это не мировой рейтинг за единый год.',
  'JODI uses the latest complete year in 2021–2025; years may differ. Missing data is not zero. Codes: 1 comparable, 2 use with caution, 3 not assessed. Crude refinery intake is processing, not final consumption. Product demand includes fuels and non-fuel uses; jet fuel is part of kerosenes.':'JODI: последний полный год за 2021–2025; годы могут различаться. Пропуск — не ноль. Оценки: 1 — сопоставимые данные, 2 — использовать с осторожностью, 3 — не оценены. Загрузка НПЗ — переработка, а не конечное потребление. Спрос включает топливное и нетопливное использование; авиакеросин входит в группу керосинов.',
};
